name: 'Birthday Check Cron Job'

on:
  schedule:
    # Runs at 8:00 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: 'Call Netlify Cron Job'
        run: |
          # ❗️ PASTE YOUR LIVE WEBSITE URL HERE
          curl --request GET \
          --url "https://your-project-name.netlify.app/.netlify/functions/cron"
