name: 'Birthday Check Cron Job'

on:
  schedule:
    # Runs at minute 0 of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: 'Call Vercel Cron Job'
        run: |
          curl --request GET \
          --url "https://YOUR_VERCEL_PROJECT_URL.vercel.app/api/cron"
